export default function favoriteArtists(): Set<string> {
    return new Set([
        "A Tribe Called Quest",
        "Aesop Rock",
        "Amon Duul",
        "Amon Duul II",
        "Area",
        "Battles",
        "Black Sabbath",
        "Can",
        "Cannibal Ox",
        "Company Flow",
        "Cut Chemist",
        "Czardust",
        "DOOM",
        "Danny Brown",
        "Edan",
        "El-P",
        "Faust",
        "Homeboy Sandman",
        "Homeboy Sandman & Edan",
        "J-Zone",
        "July",
        "Kendrick Lamar",
        "Kool Keith",
        "Madlib",
        "Madvillain",
        "Micachu & The Shapes",
        "Mono En Stereo",
        "Nirvana",
        "Pan Y Regaliz",
        "Paul White",
        "Pixies",
        "Prefuse 73",
        "Quasimoto",
        "RTNC",
        "Radian",
        "Syrinx",
        "The Bug",
        "The Pretty Things",
        "Viktor Vaughn",
        "Wiki",
        "Your Old Droog",
    ])
}